/**
 * Hirist location filter IDs, as used by the site's own location picker
 * (value passed as `loc` to /job/search). Names containing "/" are
 * matched by each part, e.g. "Gurgaon/Gurugram" matches "Gurgaon".
 */
export const HIRIST_LOCATION_IDS: Record<string, number> = {
  "Abu Dhabi": 100,
  "Afghanistan": 109,
  "Africa": 26,
  "Agra": 136,
  "Ahmedabad": 53,
  "Amritsar": 45,
  "Andaman and Nicobar Island": 162,
  "Andhra Pradesh": 34,
  "Arunachal Pradesh": 127,
  "Assam": 123,
  "Aurangabad": 79,
  "Australia": 165,
  "Baddi": 140,
  "Bahrain": 90,
  "Bangalore": 3,
  "Bangladesh": 107,
  "Bhopal": 121,
  "Bhubaneshwar": 65,
  "Bhutan": 105,
  "Bihar": 19,
  "Canada": 167,
  "Chandigarh": 14,
  "Chennai": 6,
  "Chhattisgarh": 64,
  "China": 108,
  "Cochin/Kochi": 70,
  "Coimbatore": 84,
  "Cuttack": 86,
  "Dadra and Nagar Haveli": 161,
  "Daman and Diu": 160,
  "Dehradun": 58,
  "Delhi": 36,
  "Dhaka": 106,
  "Doha": 98,
  "Dubai": 91,
  "EU": 28,
  "Egypt": 113,
  "England": 170,
  "Ethiopia": 112,
  "Faridabad": 40,
  "Gandhinagar": 55,
  "Germany": 168,
  "Ghaziabad": 41,
  "Goa": 13,
  "Greater Noida": 39,
  "Gujarat": 8,
  "Guntur": 77,
  "Gurgaon/Gurugram": 37,
  "Guwahati": 12,
  "Gwalior": 141,
  "Haridwar": 57,
  "Haryana": 16,
  "Himachal Pradesh": 153,
  "Hong Kong": 30,
  "Hosur": 71,
  "Hubli": 72,
  "Hyderabad": 4,
  "Imphal": 137,
  "Indonesia": 103,
  "Indore": 130,
  "Jaipur": 11,
  "Jalandhar": 46,
  "Jammu & Kashmir": 42,
  "Jammu": 43,
  "Jamnagar": 147,
  "Jamshedpur": 63,
  "Japan": 166,
  "Jharkhand": 20,
  "Jodhpur": 52,
  "Kabul": 92,
  "Kanpur": 133,
  "Karnataka": 31,
  "Kenya": 114,
  "Kerala": 17,
  "Kolkata": 5,
  "Kozhikode": 146,
  "Kuwait": 93,
  "Lakshadweep": 163,
  "London": 95,
  "Lucknow": 60,
  "Ludhiana": 48,
  "MP": 10,
  "Madurai": 83,
  "Maharashtra": 9,
  "Malaysia": 27,
  "Manesar": 138,
  "Mangalore": 134,
  "Manipur": 124,
  "Meghalaya": 125,
  "Middle East": 25,
  "Mizoram": 122,
  "Mohali": 131,
  "Mumbai": 2,
  "Muscat": 97,
  "Mysore": 73,
  "Nagaland": 128,
  "Nagpur": 66,
  "Nairobi": 115,
  "Nasik": 67,
  "Navi Mumbai": 68,
  "Nepal": 104,
  "Nigeria": 94,
  "Noida": 38,
  "Odisha": 18,
  "Oman": 96,
  "Pakistan": 110,
  "Panchkula": 142,
  "Panipat": 50,
  "Patiala": 47,
  "Patna": 61,
  "Philippines": 120,
  "Pondicherry": 85,
  "Pune": 7,
  "Punjab": 15,
  "Qatar": 99,
  "Raipur": 74,
  "Rajasthan": 33,
  "Rajkot": 80,
  "Ranchi": 62,
  "Remote": 132,
  "Riyadh": 102,
  "Salem": 149,
  "Saudi Arabia": 101,
  "Secunderabad": 144,
  "Shillong": 139,
  "Shimla": 152,
  "Sikkim": 158,
  "Siliguri": 143,
  "Silvassa": 135,
  "Singapore": 24,
  "Sonipat": 49,
  "South Africa": 117,
  "Sri Lanka": 111,
  "Srinagar": 44,
  "Surat": 54,
  "Switzerland": 169,
  "Tamil Nadu": 32,
  "Tanzania": 116,
  "Telangana": 35,
  "Thane": 69,
  "Tiruchirappalli": 148,
  "Tirupati": 150,
  "Tripura": 126,
  "Trivandrum/Thiruvananthapuram": 75,
  "UK": 23,
  "UP": 21,
  "US": 22,
  "Udaipur": 51,
  "Uttarakhand": 59,
  "Vadodara/Baroda": 56,
  "Vapi": 145,
  "Varanasi/Banaras": 81,
  "Vellore": 151,
  "Vijayawada": 76,
  "Vishakhapatnam/Vizag": 78,
  "Warangal": 82,
  "West Bengal": 129,
  "Zambia": 119,
  "Zimbabwe": 118,
};

/** Multi-city groups mirroring the site's picker plus common spellings. */
const GROUPS: Record<string, number[]> = {
  metros: [1, 36, 41, 40, 37, 38, 2, 5, 3, 7, 4, 6, 54, 78, 39],
  "delhi ncr": [36, 37, 38, 39, 40, 41],
  ncr: [36, 37, 38, 39, 40, 41],
  bengaluru: [3],
  bombay: [2],
  calcutta: [5],
  madras: [6],
};

function key(value: string): string {
  return value.trim().toLowerCase().replace(/\s+/g, " ");
}

const LOOKUP = new Map<string, number[]>();
for (const [name, id] of Object.entries(HIRIST_LOCATION_IDS)) {
  LOOKUP.set(key(name), [id]);
  for (const part of name.split("/")) if (!LOOKUP.has(key(part))) LOOKUP.set(key(part), [id]);
}
for (const [name, ids] of Object.entries(GROUPS)) LOOKUP.set(name, ids);

/**
 * Resolves a comma-separated location setting such as "Pune" or
 * "Pune, Bangalore, Remote" to Hirist location IDs. An empty value means
 * no location filter.
 */
export function resolveLocationIds(location: string): number[] {
  const ids = new Set<number>();
  for (const part of location.split(",").map(key).filter(Boolean)) {
    const match = LOOKUP.get(part);
    if (!match) throw new Error(`Unknown Hirist location "${part}". Use a city from src/hirist/locations.ts (e.g. Pune, Bangalore, Remote).`);
    match.forEach((id) => ids.add(id));
  }
  return [...ids];
}
